# Generated by Django 4.0.4 on 2022-04-23 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='project_image',
            new_name='profile_image',
        ),
    ]
