# Generated by Django 4.0.4 on 2022-05-05 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_alter_comment_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='plant',
            new_name='plants',
        ),
    ]
