# Generated by Django 4.0.3 on 2022-04-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=40)),
                ('description', models.CharField(default=None, max_length=300)),
                ('image', models.CharField(default=None, max_length=50)),
                ('owner', models.CharField(default=None, max_length=20)),
            ],
        ),
    ]
