# Generated by Django 4.0.4 on 2022-05-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='category',
            field=models.ManyToManyField(related_name='plant', to='category.category'),
        ),
    ]
