# Generated by Django 4.0.4 on 2022-05-05 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_alter_plant_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='owner',
        ),
    ]
