# Generated by Django 4.0.4 on 2022-05-05 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plants', '0003_remove_plant_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='plants', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
