# Generated by Django 4.0.3 on 2022-04-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('plants', '0004_alter_plant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='category',
            field=models.ManyToManyField(related_name='plants', to='category.category'),
        ),
    ]
